default: &default
  adapter: postgresql # postgresql database server
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 50000
  username: mohiuddin
  # password: nhyxp954648

development:
  <<: *default
  database: yalpdemo

test:
  <<: *default
  database: yalpdemo_test

production:
  <<: *default
  database: yalpdemo_production
